# Project Unique Keys
sonar.projectKey=sachinthokal_kube-traffic-lens-app
sonar.organization=sachinthokal

# Code path (All files scan)
sonar.sources=.

# Force pipeline to fail if Quality Gate fails
sonar.qualitygate.wait=true