name : KUBE TRAFFIC LENS CICD
on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  code-qulity:
    name: Code Quality & Security
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7
        with:
          fetch-depth: 0

      - name: Set Up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade --only-binary :all: pip
          pip install --only-binary :all: -r requirements.txt

      # 1. GitLeaks Scan Step
      - name: GitLeaks Checks
        uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e  # v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 2. Lint Step
      - name: Lint Python App
        run: python -m pylint app.py tests/

      # 3. Automated Test Cases Step
      - name: Test Cases Python App
        run: python -m pytest -v

      # 3. SonarQube Scan Step
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@ba9859eae8dd6bd29e412f25ddbbef3d032000f4  # v8.2.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

  # code-build:
  # image-scan:
  # stage-deploy:
  # prod-deploy:
  