name : KUBE TRAFFIC LENS CI
on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  code-qulity:
    name: Code Quality & Security
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set Up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: GitLeaks Checks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Python App
        run: python -m pylint app.py tests/

      - name: Test Cases Python App
        run: python -m pytest -v

  # code-build:
  # image-scan:
  # stage-deploy:
  # prod-deploy:
  