name : KUBE TRAFFIC LENS CI
on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  code-qulity:
    name: Code Quality & Security
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: GitLeaks Checks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Repo Verify
        run: |
          pwd
          echo "======="
          python -v
          docker -v
          echo "======="
          ls -ltr
          echo "======="

  # code-build:
  # image-scan:
  # stage-deploy:
  # prod-deploy:
  